#tests:
#- echo "Hello, world!"> hello.txt
#- pwd
#- cat hello.txt
#- ls -lash
tests:
- chmod +x install_salt.sh
- ./install_salt.sh
#- curl -L https://bootstrap.saltstack.com | sudo sh -s -- git develop
